// <auto-generated />
using EFDemo.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFDemo.Migrations
{
    [DbContext(typeof(CourseContext))]
    [Migration("20220216094631_SeedInitialData")]
    partial class SeedInitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFDemo.Model.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "DW",
                            Naam = "Discrete Wiskunde"
                        },
                        new
                        {
                            Id = 2,
                            Code = "GP",
                            Naam = "Games Programming"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ANA1",
                            Naam = "Analyse 1"
                        },
                        new
                        {
                            Id = 4,
                            Code = "ANA2",
                            Naam = "Analyse 2"
                        },
                        new
                        {
                            Id = 5,
                            Code = "C#",
                            Naam = "C-sharp"
                        },
                        new
                        {
                            Id = 6,
                            Code = "GESP",
                            Naam = "Gesprekken in Organisaties"
                        },
                        new
                        {
                            Id = 7,
                            Code = "WP",
                            Naam = "Web programmeren"
                        },
                        new
                        {
                            Id = 8,
                            Code = "PYT",
                            Naam = "Python"
                        },
                        new
                        {
                            Id = 9,
                            Code = "JAV",
                            Naam = "Java programmeren"
                        },
                        new
                        {
                            Id = 10,
                            Code = "ISEC",
                            Naam = "Inleiding Security"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
